meta_product_name: "Renbo"
meta_title: "Renbo - Buy event tickets as NFTs | Sell your tickets | Collect"
meta_description: "A NFT ticketing marketplace where you can buy, sell and collect NFTs"
meta_image: "renbologo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards