meta_product_name: "Renbo"
meta_title: "Renbo - Collectible | Colourful | Conscientious Tickets"
meta_description: "A NFT ticketing marketplace where you can buy, sell and collect NFTs"
meta_image: "renbologo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
